spring:
  profiles:
    active: dev

server:
  port: 8085

mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/*/*.xml
  configLocation: classpath:/mybatis-config.xml

---
spring:
  profiles: dev
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/ejabberd
    username: ejabberd
    password: 123456
    driver-class-name: org.postgresql.Driver

---
spring:
  profiles: test

server:
  port: 8081

---
spring:
  profiles: prod

server:
  port: 8081